import React, { useCallback, useEffect, useState } from "react";
import { Button, Form } from "@themesberg/react-bootstrap";
import { operatorRepository } from "../../../lib/data";
import { isBackendSiteId } from "../../../lib/data/siteIdUtils";
import { classifyOperatorPointKind } from "../../../lib/operator/pointKind";

const TEMPLATE_KEY = "legion.logicTemplates.v1";
const STEPS = ["Inputs", "Condition", "Actions", "Details"];
const OPERATORS = [["GT", "is greater than"], ["GTE", "is at least"], ["LT", "is less than"], ["LTE", "is at most"], ["EQ", "equals"], ["NEQ", "does not equal"], ["IS_ON", "is ON"], ["IS_OFF", "is OFF"]];
const PRESETS = [
  { name: "High Limit", category: "THRESHOLD", operator: "GT", message: "High limit" },
  { name: "Low Limit", category: "THRESHOLD", operator: "LT", message: "Low limit" },
  { name: "Binary State Alarm", category: "BINARY", operator: "IS_OFF", message: "Unexpected state" },
  { name: "Command/Status Mismatch", category: "COMPARISON", operator: "NEQ", message: "Command and status mismatch" },
  { name: "Custom Logic", category: "THRESHOLD", operator: "GT", message: "Alarm" },
];

function loadTemplates() { try { return JSON.parse(window.localStorage.getItem(TEMPLATE_KEY) || "[]"); } catch { return []; } }
function saveTemplates(rows) { window.localStorage.setItem(TEMPLATE_KEY, JSON.stringify(rows)); }
function pointLabel(point) { return point?.pointDescription || point?.pointName || point?.pointKey || point?.pointId || "Point"; }
function pointType(point) { const kind = classifyOperatorPointKind(point); return kind === "analog" ? "Analog" : kind === "multistate" ? "Multi-State" : "Binary"; }
function emptyForm() { return { name: "", category: "THRESHOLD", operator: "GT", threshold: "", delay: "", deadband: "", severity: "WARNING", message: "", enabled: true, trueAction: "Raise Alarm", falseAction: "Clear Alarm", combine: "AND" }; }
function definitionTemplate(def, points, equipment) {
  const source = points.find((point) => String(point.databasePointId || point.id) === String(def.pointId) || String(point.pointKey) === String(def.pointKey));
  return { id: `rule-${def.id}`, version: 1, name: def.name || "Alarm Rule", equipmentType: equipment.type || equipment.equipmentType || "", inputs: source ? [{ key: "A", role: pointLabel(source), type: pointType(source), pointKey: source.pointKey || source.pointId }] : [{ key: "A", role: def.pointKey || "Input A", type: "Analog", pointKey: def.pointKey }], logic: { ...emptyForm(), name: def.name || "", category: def.category || "THRESHOLD", operator: def.operator || "GT", threshold: def.targetValue == null ? "" : String(def.targetValue), delay: def.delaySeconds == null ? "" : String(def.delaySeconds), deadband: def.deadband == null ? "" : String(def.deadband), severity: def.severity || "WARNING", message: def.messageTemplate || "", enabled: def.enabled !== false }, assignments: [String(equipment.id)] };
}

function StepProgress({ step, onStep }) {
  return <ol className="logic-wizard__progress" aria-label="Rule steps">{STEPS.map((label, index) => <li key={label} className={`${index === step ? "is-current" : ""}${index < step ? " is-complete" : ""}`}><button type="button" onClick={() => index <= step && onStep(index)} aria-current={index === step ? "step" : undefined}><span>{index + 1}</span>{label}</button></li>)}</ol>;
}

function InputsStep({ points, selected, setSelected }) {
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("all");
  const rows = points.filter((point) => { const kind = classifyOperatorPointKind(point); return (filter === "all" || kind === filter) && `${pointLabel(point)} ${point.pointKey || ""}`.toLowerCase().includes(search.toLowerCase()); });
  const add = (point) => { if (!selected.some((item) => String(item.id) === String(point.id))) setSelected([...selected, point]); };
  return <div className="logic-wizard__inputs"><div><h2>Select input points</h2><p className="text-muted">Choose one or more equipment points to use in this rule.</p><Form.Control placeholder="Search equipment points…" value={search} onChange={(e) => setSearch(e.target.value)} /><div className="logic-wizard__filters">{[["all", "All"], ["analog", "Analog"], ["binary", "Binary"], ["multistate", "Multi-State"]].map(([id, label]) => <button type="button" className={filter === id ? "is-active" : ""} key={id} onClick={() => setFilter(id)}>{label}</button>)}</div><div className="logic-point-list">{rows.map((point) => <div className="logic-point-row" key={point.id}><div><strong>{pointLabel(point)}</strong><span>{point.pointKey || point.pointId} · {pointType(point)} · {point.value ?? "—"}</span></div><Button size="sm" variant="link" onClick={() => add(point)} disabled={selected.some((item) => String(item.id) === String(point.id))}>+</Button></div>)}</div></div><aside className="logic-wizard__selected"><h2>Selected Inputs</h2>{selected.length ? selected.map((point, index) => <div className="logic-selected-row" key={point.id}><span className="logic-input__key">{String.fromCharCode(65 + index)}</span><div><strong>{pointLabel(point)}</strong><span>{point.pointKey || point.pointId} · {pointType(point)}</span></div><Button variant="link" size="sm" onClick={() => setSelected(selected.filter((item) => String(item.id) !== String(point.id)))} aria-label={`Remove ${pointLabel(point)}`}>×</Button></div>) : <p className="text-muted small">Add points from the list.</p>}<div className="logic-wizard__help">Add the equipment points used by the rule. You can add more inputs later.</div></aside></div>;
}

function ConditionStep({ selected, form, setForm }) {
  const [conditions, setConditions] = useState(() => selected[0] ? [{ input: 0, operator: form.operator, value: form.threshold }] : []);
  useEffect(() => { if (selected.length && conditions.length === 0) setConditions([{ input: 0, operator: form.operator, value: form.threshold }]); }, [selected.length, conditions.length, form.operator, form.threshold]);
  const update = (index, patch) => { const next = conditions.map((condition, i) => i === index ? { ...condition, ...patch } : condition); setConditions(next); const first = next[0] || {}; setForm({ ...form, operator: first.operator || form.operator, threshold: first.value ?? form.threshold }); };
  return <div className="logic-wizard__step"><div className="logic-wizard__intro"><span className="logic-wizard__kicker">WHEN</span><h2>Define the condition</h2><p>Use the selected points and supported operators to describe when this rule is true.</p></div>{conditions.map((condition, index) => <React.Fragment key={index}>{index > 0 ? <div className="logic-condition-join"><Form.Control as="select" value={form.combine} onChange={(e) => setForm({ ...form, combine: e.target.value })}><option>AND</option><option>OR</option></Form.Control></div> : null}<div className="logic-condition logic-condition--wizard"><Form.Control as="select" value={condition.input} onChange={(e) => update(index, { input: Number(e.target.value) })}>{selected.map((point, i) => <option key={point.id} value={i}>{String.fromCharCode(65 + i)} – {pointLabel(point)}</option>)}</Form.Control><Form.Control as="select" value={condition.operator} onChange={(e) => update(index, { operator: e.target.value })}>{OPERATORS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Form.Control>{!["IS_ON", "IS_OFF"].includes(condition.operator) ? <Form.Control placeholder="Value" value={condition.value} onChange={(e) => update(index, { value: e.target.value })} /> : null}<span>{selected[condition.input]?.unit || "value"}</span></div></React.Fragment>)}<Button variant="outline-secondary" size="sm" onClick={() => selected.length > conditions.length && setConditions([...conditions, { input: conditions.length, operator: "EQ", value: "" }])} disabled={selected.length < 2}>+ Add Condition</Button><div className="logic-delay"><Form.Label>Condition must remain true for</Form.Label><Form.Control type="number" min="0" value={form.delay} onChange={(e) => setForm({ ...form, delay: e.target.value })} /><span>seconds</span></div>{selected.length > 1 ? <p className="text-muted small mt-3">Additional conditions are retained for template review and require a runtime evaluator that supports condition trees before deployment.</p> : null}</div>;
}

function ActionsStep({ form, setForm }) { return <div className="logic-wizard__step"><div className="logic-wizard__intro"><span className="logic-wizard__kicker">RESULT</span><h2>Choose what happens</h2><p>Actions are evaluated by the alarm runtime. Equipment output writes are not exposed here.</p></div><div className="logic-action-grid"><label><span>WHEN TRUE</span><Form.Control as="select" value={form.trueAction} onChange={(e) => setForm({ ...form, trueAction: e.target.value })}><option>Raise Alarm</option><option>No Action</option></Form.Control></label><label><span>WHEN FALSE</span><Form.Control as="select" value={form.falseAction} onChange={(e) => setForm({ ...form, falseAction: e.target.value })}><option>Clear Alarm</option><option>No Action</option></Form.Control></label></div></div>; }
function DetailsStep({ form, setForm, saving, save, saveTemplate, onDelete }) { return <div className="logic-wizard__step"><div className="logic-wizard__intro"><span className="logic-wizard__kicker">FINAL CONFIGURATION</span><h2>Rule details</h2><p>Give the rule a clear name and configure its alarm metadata.</p></div><div className="logic-details-grid"><Form.Group><Form.Label>Alarm Name</Form.Label><Form.Control value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Form.Group><Form.Group><Form.Label>Message</Form.Label><Form.Control value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} /></Form.Group><Form.Group><Form.Label>Priority / Severity</Form.Label><Form.Control as="select" value={form.severity} onChange={(e) => setForm({ ...form, severity: e.target.value })}><option value="WARNING">Warning</option><option value="MINOR">Minor</option><option value="MAJOR">Major</option><option value="CRITICAL">Critical</option></Form.Control></Form.Group><Form.Group><Form.Label>Analog deadband</Form.Label><Form.Control value={form.deadband} onChange={(e) => setForm({ ...form, deadband: e.target.value })} /></Form.Group><Form.Check type="switch" label="Enabled" checked={form.enabled} onChange={(e) => setForm({ ...form, enabled: e.target.checked })} /></div><div className="logic-wizard__save-row"><Button variant="outline-secondary" onClick={saveTemplate}>Save as Template</Button>{onDelete ? <Button variant="link" className="text-danger" onClick={onDelete}>Delete Rule</Button> : null}<Button variant="primary" disabled={saving} onClick={save}>{saving ? "Saving…" : "Save Rule"}</Button></div></div>; }

export default function EquipmentAlarmWorkspace({ equipment, points, alarms = [], releaseData, siteKey, initialPoint, onBack, onSaved }) {
  const [definitions, setDefinitions] = useState([]); const [templates, setTemplates] = useState(loadTemplates); const [tab, setTab] = useState("rules"); const [step, setStep] = useState(0); const [selectedDef, setSelectedDef] = useState(null); const [selected, setSelected] = useState(() => initialPoint ? [initialPoint] : []); const [form, setForm] = useState(emptyForm); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [assignments, setAssignments] = useState({});
  const equipmentList = releaseData?.equipment || []; const equipmentId = equipment?.id; const activeCount = alarms.filter((a) => String(a.equipmentId) === String(equipmentId) && String(a.state).toUpperCase() === "ACTIVE").length;
  const refresh = useCallback(async () => { if (!isBackendSiteId(siteKey) || !equipmentId) return; try { const nextDefinitions = await operatorRepository.listOperatorAlarmDefinitions(siteKey, { equipmentId }) || []; setDefinitions(nextDefinitions); if (nextDefinitions.length) { const generated = nextDefinitions.map((definition) => definitionTemplate(definition, points, equipment)); const generatedIds = new Set(generated.map((item) => item.id)); const generatedNames = new Set(generated.map((item) => item.name.toLowerCase())); setTemplates((current) => { const merged = [...current.filter((item) => !generatedIds.has(item.id) && !generatedNames.has(String(item.name || "").toLowerCase())), ...generated]; saveTemplates(merged); return merged; }); } } catch (e) { setError(e.message || String(e)); } }, [siteKey, equipmentId, points, equipment]);
  useEffect(() => { refresh(); }, [refresh]); useEffect(() => { if (initialPoint && !selected.some((point) => String(point.id) === String(initialPoint.id))) setSelected([initialPoint]); }, [initialPoint, selected]);
  const reset = (preset = {}) => { const defaultPreset = PRESETS.find((item) => item.name === "Custom Logic"); setSelectedDef(null); setStep(0); setForm({ ...emptyForm(), category: defaultPreset?.category || "THRESHOLD", operator: defaultPreset?.operator || "GT", message: defaultPreset?.message || "", ...preset }); setError(""); };
  const edit = (def) => { const source = points.find((p) => String(p.databasePointId || p.id) === String(def.pointId) || String(p.pointKey) === String(def.pointKey)); setSelectedDef(def); setSelected(source ? [source] : []); setForm({ ...emptyForm(), name: def.name || "", category: def.category || "THRESHOLD", operator: def.operator || "GT", threshold: def.targetValue == null ? "" : String(def.targetValue), delay: def.delaySeconds == null ? "" : String(def.delaySeconds), deadband: def.deadband == null ? "" : String(def.deadband), severity: def.severity || "WARNING", message: def.messageTemplate || "", enabled: def.enabled !== false }); setStep(0); setTab("rules"); };
  const selectTemplate = (template) => { setSelectedDef(null); setSelected(template.inputs.map((input) => points.find((p) => String(p.pointKey || p.pointId) === String(input.pointKey))).filter(Boolean)); setForm({ ...emptyForm(), ...(template.logic || {}), name: template.name }); setTab("rules"); setStep(0); };
  const save = async () => { if (!selected[0] || !form.name.trim()) { setError("Choose Input A and provide an alarm name in Details."); return; } if (selected.length > 1) { setError("The current runtime evaluator safely deploys one source condition per alarm. Keep additional inputs for template review before deployment."); return; } setSaving(true); setError(""); try { const source = selected[0]; const payload = { equipmentId: String(equipment.id), pointKey: String(source.pointKey || source.pointId), pointId: source.databasePointId || null, name: form.name.trim(), category: form.category, operator: form.operator, targetValue: form.threshold === "" ? null : Number(form.threshold), delaySeconds: form.delay === "" ? null : Number(form.delay), deadband: form.deadband === "" ? null : Number(form.deadband), severity: form.severity, messageTemplate: form.message.trim() || null, enabled: form.enabled, autoAcknowledge: false }; if (selectedDef) await operatorRepository.updateOperatorAlarmDefinition(siteKey, selectedDef.id, payload); else await operatorRepository.createOperatorAlarmDefinition(siteKey, payload); const template = { id: `tpl-${form.name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, version: 1, name: form.name.trim(), equipmentType: equipment.type || equipment.equipmentType || "", inputs: selected.map((point, index) => ({ key: String.fromCharCode(65 + index), role: pointLabel(point), type: pointType(point), pointKey: point.pointKey || point.pointId })), logic: { ...form }, assignments: [String(equipment.id)] }; const existingTemplate = templates.find((item) => item.name.toLowerCase() === template.name.toLowerCase()); const nextTemplates = existingTemplate ? templates.map((item) => item.id === existingTemplate.id ? { ...item, ...template, id: item.id, version: (item.version || 1) + (selectedDef ? 0 : 1) } : item) : [...templates, template]; setTemplates(nextTemplates); saveTemplates(nextTemplates); notifyAlarmChange(); await refresh(); if (onSaved) onSaved(); reset(); } catch (e) { setError(e.message || String(e)); } finally { setSaving(false); } };
  const saveTemplate = () => { if (!selected[0] || !form.name.trim()) { setError("Choose inputs and provide a name before saving a template."); return; } const next = [...templates, { id: `tpl-${Date.now()}`, version: 1, name: form.name.trim(), equipmentType: equipment.type || equipment.equipmentType || "", inputs: selected.map((point, index) => ({ key: String.fromCharCode(65 + index), role: pointLabel(point), type: pointType(point), pointKey: point.pointKey || point.pointId })), logic: { ...form }, assignments: [] }]; setTemplates(next); saveTemplates(next); setTab("templates"); };
  const compatible = (eq, template) => String(eq.type || eq.equipmentType || "").toUpperCase() === String(template.equipmentType || "").toUpperCase(); const resolveTemplatePoint = (eq, input) => { const rows = operatorRepository.getWorkspacePointsForEquipment(eq.id, eq.displayLabel || eq.name, eq.status, { activeRelease: releaseData }); return rows.find((p) => String(p.pointKey || p.pointId || "").toUpperCase() === String(input.pointKey || "").toUpperCase()) || rows.find((p) => pointLabel(p).toLowerCase() === String(input.role || "").toLowerCase()) || null; };
  const notifyAlarmChange = () => window.dispatchEvent(new Event("legion:operator-alarms-changed"));
  const deleteRule = async () => { if (!selectedDef || !window.confirm(`Delete ${selectedDef.name || "this rule"}?`)) return; await operatorRepository.deleteOperatorAlarmDefinition(siteKey, selectedDef.id); notifyAlarmChange(); await refresh(); reset(); };
  const deleteTemplate = async (template) => {
    if (!window.confirm(`Delete ${template.name || "this template"} and all assigned alarms?`)) return;
    try {
      const equipmentIds = [...new Set([String(equipment.id), ...(template.assignments || []).map(String), ...equipmentList.map((item) => String(item.id))])];
      const definitions = (await Promise.all(equipmentIds.map((id) => operatorRepository.listOperatorAlarmDefinitions(siteKey, { equipmentId: id }).catch(() => [])))).flat();
      const matching = definitions.filter((definition) => String(definition.name || "").toLowerCase() === String(template.name || "").toLowerCase());
      await Promise.all(matching.map((definition) => operatorRepository.deleteOperatorAlarmDefinition(siteKey, definition.id)));
      const next = templates.filter((item) => item.id !== template.id);
      setTemplates(next); saveTemplates(next); notifyAlarmChange(); await refresh();
    } catch (e) { setError(e.message || String(e)); }
  };
  const deploy = async (template) => { const chosen = equipmentList.filter((eq) => assignments[`${template.id}:${eq.id}`] && compatible(eq, template)); const resolved = chosen.map((eq) => ({ eq, points: template.inputs.map((input) => resolveTemplatePoint(eq, input)) })); if (!chosen.length) { setError("Select compatible equipment with ready mappings before deployment."); return; } if (resolved.some((row) => row.points.some((point) => !point))) { setError("One or more assignments require point mapping. No rules were deployed."); return; } if (!window.confirm(`Deploy ${template.name} to ${chosen.length} equipment?`)) return; try { for (const row of resolved) { const source = row.points[0]; const logic = template.logic || {}; await operatorRepository.createOperatorAlarmDefinition(siteKey, { equipmentId: String(row.eq.id), pointKey: String(source.pointKey || source.pointId), pointId: source.databasePointId || null, name: template.name, category: logic.category || "THRESHOLD", operator: logic.operator || "GT", targetValue: logic.threshold === "" ? null : Number(logic.threshold), delaySeconds: logic.delay === "" ? null : Number(logic.delay), deadband: logic.deadband === "" ? null : Number(logic.deadband), severity: logic.severity || "WARNING", messageTemplate: logic.message || template.name, enabled: logic.enabled !== false, autoAcknowledge: false }); } setError(`Deployed ${template.name} to ${resolved.length} equipment.`); } catch (e) { setError(e.message || String(e)); } };
  const ruleIndex = definitions.findIndex((def) => String(def.id) === String(selectedDef?.id)); const currentDef = definitions[ruleIndex] || null;
  return <section className="operator-full-workspace alarm-workspace" aria-label="Alarms and Logic workspace"><div className="operator-full-workspace__topbar"><Button variant="link" className="operator-back-link" onClick={onBack}>← Back to Equipment</Button><span className="operator-eyebrow">ALARMS &amp; LOGIC</span></div><div className="operator-editor-panel logic-wizard"><div className="logic-wizard__toolbar"><div className="operator-workspace-tabs"><button className={tab === "rules" ? "is-active" : ""} onClick={() => setTab("rules")}>Rules</button><button className={tab === "templates" ? "is-active" : ""} onClick={() => setTab("templates")}>Templates</button><button className={tab === "assignments" ? "is-active" : ""} onClick={() => setTab("assignments")}>Assignments</button></div>{tab === "rules" ? <div className="logic-wizard__rule-tools"><Form.Control as="select" size="sm" aria-label="Rule name" value={selectedDef?.id || ""} onChange={(e) => { const def = definitions.find((item) => String(item.id) === e.target.value); if (def) edit(def); }}><option value="">{definitions.length ? "New rule" : (form.name || "New rule")}</option>{definitions.map((def) => <option key={def.id} value={def.id}>{def.name}</option>)}</Form.Control></div> : null}</div>{tab === "rules" ? <><StepProgress step={step} onStep={setStep}/><div className="logic-wizard__context">{selectedDef ? `Editing ${selectedDef.name}` : selected.length ? `Building a rule for ${equipment?.displayLabel || equipment?.name}` : "New alarm rule"} · {activeCount} active</div>{step === 0 ? <InputsStep points={points} selected={selected} setSelected={setSelected}/> : null}{step === 1 ? <ConditionStep selected={selected} form={form} setForm={setForm}/> : null}{step === 2 ? <ActionsStep form={form} setForm={setForm}/> : null}{step === 3 ? <DetailsStep form={form} setForm={setForm} saving={saving} save={save} saveTemplate={saveTemplate} onDelete={selectedDef ? deleteRule : null}/> : null}{error ? <div className="alert alert-warning py-2 mt-3">{error}</div> : null}<div className="logic-wizard__footer"><Button variant="link" onClick={onBack}>Cancel</Button><div><Button variant="outline-secondary" disabled={step === 0} onClick={() => setStep(Math.max(0, step - 1))}>Back</Button>{step < 3 ? <Button variant="primary" className="ms-2" disabled={step === 0 && selected.length === 0} onClick={() => setStep(step + 1)}>Next</Button> : null}</div></div></> : null}{tab === "templates" ? <TemplateLibrary templates={templates} onOpen={selectTemplate} onDelete={deleteTemplate}/> : null}{tab === "assignments" ? <AssignmentLibrary templates={templates} equipmentList={equipmentList} assignments={assignments} setAssignments={setAssignments} compatible={compatible} resolveTemplatePoint={resolveTemplatePoint} deploy={deploy}/> : null}</div></section>;
}

function TemplateLibrary({ templates, onOpen, onDelete }) { return <div className="logic-library"><div className="logic-library__heading"><h2>Logic Templates</h2></div>{templates.length ? templates.map((template) => <div className="alarm-rule-row" key={template.id}><div><strong>{template.name}</strong><span>{template.equipmentType || "Any type"} · v{template.version} · {template.inputs.length} inputs</span></div><Button size="sm" variant="link" onClick={() => onOpen(template)}>Open / Edit</Button><Button size="sm" variant="link" onClick={() => onDelete(template)} className="text-danger">Delete</Button></div>) : <p className="text-muted">Save a rule as a template to begin.</p>}</div>; }
function AssignmentLibrary({ templates, equipmentList, assignments, setAssignments, compatible, resolveTemplatePoint, deploy }) {
  const [search, setSearch] = useState("");
  const [onlyCompatible, setOnlyCompatible] = useState(true);
  const [chosenEquipment, setChosenEquipment] = useState({});
  const updateAssignment = (template, equipment, checked) => setAssignments({ ...assignments, [`${template.id}:${equipment.id}`]: checked });
  return <div className="logic-library"><div className="logic-library__heading"><h2>Template Assignments</h2></div><div className="assignment-toolbar"><Form.Control size="sm" placeholder="Search equipment..." value={search} onChange={(e) => setSearch(e.target.value)} /><label><input type="checkbox" checked={onlyCompatible} onChange={(e) => setOnlyCompatible(e.target.checked)} /> Compatible only</label></div>{templates.length ? templates.map((template) => { const candidates = equipmentList.filter((equipment) => { const ready = compatible(equipment, template) && template.inputs.every((input) => resolveTemplatePoint(equipment, input)); return (!onlyCompatible || ready) && (equipment.displayLabel || equipment.name || "").toLowerCase().includes(search.toLowerCase()); }); const selectedRows = equipmentList.filter((equipment) => assignments[`${template.id}:${equipment.id}`]); const mappingRequired = candidates.filter((equipment) => !compatible(equipment, template) || !template.inputs.every((input) => resolveTemplatePoint(equipment, input))).length; const selectedId = chosenEquipment[template.id] || ""; return <div className="assignment-block" key={template.id}><div className="assignment-block__heading"><h3>{template.name} <small>v{template.version}</small></h3><span>{selectedRows.length} selected</span></div><div className="assignment-picker"><Form.Control as="select" size="sm" value={selectedId} onChange={(e) => setChosenEquipment({ ...chosenEquipment, [template.id]: e.target.value })}><option value="">Select equipment to assign...</option>{candidates.filter((equipment) => !assignments[`${template.id}:${equipment.id}`]).map((equipment) => <option key={equipment.id} value={equipment.id}>{equipment.displayLabel || equipment.name}</option>)}</Form.Control><Button size="sm" variant="outline-secondary" disabled={!selectedId} onClick={() => { const equipment = equipmentList.find((item) => String(item.id) === String(selectedId)); if (equipment) updateAssignment(template, equipment, true); setChosenEquipment({ ...chosenEquipment, [template.id]: "" }); }}>Add</Button></div>{mappingRequired > 0 ? <div className="assignment-mapping-note">{mappingRequired} equipment require mapping or are incompatible.</div> : null}<div className="assignment-selected">{selectedRows.length ? selectedRows.map((equipment) => <span key={equipment.id}>{equipment.displayLabel || equipment.name}<button type="button" aria-label={`Remove ${equipment.displayLabel || equipment.name}`} onClick={() => updateAssignment(template, equipment, false)}>×</button></span>) : <span className="text-muted">No equipment selected.</span>}</div><Button size="sm" variant="primary" onClick={() => deploy(template)}>Deploy selected</Button></div>; }) : <p className="text-muted">Create a template before assigning logic.</p>}</div>;
}
